// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package database

import (
	"database/sql"
	"time"
)

type Order struct {
	ID        string
	Ispaid    bool
	Userid    string
	Email     sql.NullString
	Name      sql.NullString
	Country   string
	Address   string
	Createdat time.Time
	Updatedat time.Time
}

type Orderitem struct {
	ID        string
	Orderid   string
	Productid string
	Quantity  int32
}

type Product struct {
	ID          string
	Name        string
	Description string
	Image       string
	Price       float64
	Createdat   time.Time
	Updatedat   time.Time
	Stock       int32
}

type User struct {
	ID        string
	Email     string
	Name      string
	Password  sql.NullString
	Createdat time.Time
	Updatedat time.Time
	Isadmin   bool
}
